### ISSUE TITLE
As an LA I can see the landing page

### ISSUE THREAD

**Issue by markhobson** [acteng/update-your-capital-schemes#1]
As an LA I can see the landing page so that I can understand the purpose of the service.

## Tasks

- [x] Basic Flask app 
- [x] Landing page 
- [x] GOV.UK Design System
- [x] Integration tests 
- [x] e2e tests 
- [x] GitHub Actions CI
- [x] Terraform state
- [x] Docker repository
- [x] Cloud Run deployment
- [x] Dev/Test environments
- [x] Basic Auth
