### ISSUE TITLE
Release 1.0.0

### ISSUE THREAD

**Issue by markhobson** [acteng/update-your-capital-schemes#116]
Release 1.0.0 for Private Beta.

## Tasks

- [x] Check lookup tables
- [x] Check users authority ids
- [x] Release 1.0.0-rc1
- [x] Release schemes-data 1.0.0-rc1
- [x] Promote 1.0.0-rc1:
    - [x] Deploy 1.0.0-rc1 to test
    - [x] Update users on test
    - [x] Deploy 1.0.0-rc1 to prod
    - [x] Update users on prod
- [x] Release 1.0.0
- [x] Release schemes-data 1.0.0
- [x] Promote 1.0.0:
    - [x] Deploy 1.0.0 to test
    - [x] Update users on test
    - [x] Deploy 1.0.0 to prod
    - [x] Update users on prod
