### ISSUE TITLE
Offline database backups

### ISSUE THREAD

**Issue by markhobson** [acteng/update-your-capital-schemes#160]
We have automated database backups (#97) but also need [cold or offline database backups too for disaster recovery](https://gds-way.digital.cabinet-office.gov.uk/standards/disaster-recovery.html#have-cold-or-offline-backups).

**Comment by markhobson** [comment]
NCSC guidance: https://www.ncsc.gov.uk/blog-post/offline-backups-in-an-online-world

**Comment by markhobson** [comment]
### Tasks

- [ ] Store database password as secret
- [ ] Compress dump
- [ ] Encrypt dump using passphrase in Bitwarden
- [ ] Timestamp dump
- [ ] Document backup script
- [ ] Test restoring locally
- [ ] Test restoring in GCP
- [ ] Backup prod database off GCP
