### ISSUE TITLE
As an LA I can log into the application and see the homepage

### ISSUE THREAD

**Issue by markhobson** [acteng/update-your-capital-schemes#2]
As an LA I can log into the application and see the homepage so that the service can identify me.

## Tasks

- [x] GOV.UK One Login service registration
- [x] Homepage
- [x] OIDC login
- [x] Stub OIDC server
- [x] [Show logged in user in header](https://www.sign-in.service.gov.uk/documentation/design-recommendations/let-users-navigate-sign-out)
- [x] Redirect root to homepage when authenticated
