### ISSUE TITLE
Configure GOV.UK One Login for production

### ISSUE THREAD

**Issue by Sparrow0hawk** [acteng/update-your-capital-schemes#96]
Configuration production to use the [live GOV.UK One Login environment](https://docs.sign-in.service.gov.uk/go-live/) instead of their integration environment.

## Tasks

- [x] Complete GOV.UK One Login production readiness checklist
    - [x] Confirm authorization endpoint error behaviour
    - [x] Ensure ID token iss claim matches provider configuration issuer
    - [x] Ensure ID token aud claim matches client id
    - [x] Ensure ID token signature is validated
    - [x] Ensure ID token exp claim is in the future
    - [x] Ensure ID token iat claim is in the past
    - [x] Ensure ID token nonce claim matches generated value
    - [x] Confirm token endpoint error behaviour
    - [ ] Ensure userinfo sub claim matches ID token sub claim
    - [x] Confirm userinfo endpoint error behaviour
- [x] Register client with GOV.UK One Login
- [x] Obtain and configure client id in production
- [x] Configure ODIC endpoints for live GOV.UK One Login in production
